services:
  ubuntu-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-ubuntu-container
    volumes:
      - ./src:/app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
    command: /bin/bash
    tty: true
    stdin_open: true

volumes:
  app: